.Dd January 31, 2025
.Dt SYSINFO 1
.Os
.Sh NAME
.Nm sysinfo
.Nd display system information
.Sh SYNOPSIS
.Nm
.Op Fl Chnv
.Sh DESCRIPTION
The
.Nm
utility displays system information in a formatted output.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl C
Disable color output
.It Fl h
Display help message and exit
.It Fl n
Disable ASCII art
.It Fl v
Display version information and exit
.El
.Sh OUTPUT
.Bl -tag -width Ds
.It Sy User@Hostname
Current user and system hostname from
.Ev USER
or
.Xr id 1
output, and
.Xr hostname 1
.It Sy OS
Operating system version from
.Xr uname 1
.It Sy Kernel
Kernel version from
.Xr uname 1
.It Sy Machine
Architecture and virtualization type if detected
.It Sy CPU
Processor model and number of online CPU cores
.It Sy GPU
Graphics processor information when available
.It Sy Memory
Memory usage showing used/total with percentage
.It Sy Disk
Root partition usage
.It Sy Shell
Current user's shell
.It Sy Uptime
System uptime formatted as days (d), hours (h), minutes (m)
.It Sy Packages
Number of installed packages
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev NO_COLOR
Disable color output if this variable exists (even if empty)
.It Ev SHELL
User's shell path
.It Ev USER
Username for display
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Successful completion
.It 1
Invalid command line option provided
.El
.Sh EXAMPLES
Display system information:
.Pp
.Dl $ sysinfo
.Pp
Without colors:
.Pp
.Dl $ sysinfo -C
.Pp
Without ASCII art:
.Pp
.Dl $ sysinfo -n
.Sh SEE ALSO
.Xr df 1 ,
.Xr hostname 1 ,
.Xr id 1 ,
.Xr pkg_info 1 ,
.Xr sysctl 8 ,
.Xr uname 1 ,
.Xr vmstat 1
.Sh AUTHORS
.An Szenesis Aq Mt https://github.com/Szenesis/sysinfo
.Pp
Modified by
.An Dair Aidarkhanov Aq Mt https://github.com/telesvar/sysinfo
.Sh LICENSE
MIT License
.br
Copyright (c) 2023 Szenesis
.br
Copyright (c) 2024 Dair Aidarkhanov
